server:
  port: 8080
website:
  name: 简单的spring boot
  domain: https://www.jaminhuang.com
  msg: 这是一个简单的spring boot 框架
spring:
  datasource:
    name: demo
    url: jdbc:mysql://103.40.29.133:3306/ElimSign
    username: jaminhuang
    password: opN9d1t3AUQ#Kzyy
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.springboot.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
