server:
  port: 8080
website:
  name: 简单的spring boot
  domain: https://www.jaminhuang.com
  msg: 这是一个简单的spring boot 框架
spring:
  datasource:
    url: jdbc:mysql://103.40.29.133:3306/ElimSign
    username: jaminhuang
    password: opN9d1t3AUQ#Kzyy
    driver-class-name: com.mysql.jdbc.Driver
